name: ocean-data-toolbox
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - jupyter
  - pandas
  - xarray
  - scipy=1.5.3
  - cmocean
  - pip=23.0
  - jupyterlab
  - pip:
      - cftime==1.6.0
      - gsw==3.6.16
      - markdown==3.3.4
      - markdown2==2.4.2
      - markdown2pdf==0.1.4
      - mat4py==0.5.0
      - scp==0.14.4
      - seawater==3.3.4